# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - 3.6.0
  - release
  - devel
warnings_are_errors: true
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr

dist: xenial
addons:
  apt:
    packages: libnode-dev

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

before_script:
  - Rscript -e "modeltime.gluonts::install_gluonts()"

after_success:
  - Rscript -e 'covr::codecov()'

